name: The Mortgage Handbook
favicon: null
layout_spectrum: 1
typography_spectrum: 0.77205
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9ba3b6'
    - '#2c2d27'
    - '#54604c'
    - '#d9e6f7'
    - '#bb7a5e'
  brandStrength: 0.5
  lightness: 0.6297593950293958
  saturation: 0.5733362876344472
  rhythmicContrast: 0.38059015152975917
purpose: []
